apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: gitops-system
    app.kubernetes.io/version: latest
    control-plane: controller
  name: notification-controller
  namespace: gitops-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: notification-controller
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: gitops-system
    app.kubernetes.io/version: latest
    control-plane: controller
  name: source-controller
  namespace: gitops-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: source-controller
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: gitops-system
    app.kubernetes.io/version: latest
    control-plane: controller
  name: webhook-receiver
  namespace: gitops-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-webhook
  selector:
    app: notification-controller
  type: ClusterIP
