apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "limits"
spec:
  limits:
    - type: "Container"
      defaultRequest:
        cpu: "25m"
        memory: 100Mi
      default:
        memory: 1Gi
