apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  clusterLabel1: someValue1
resources:
  - ../../common/cluster
# example on how to patch a value in base
patchesJson6902:
- target:
    version: v1
    kind: LimitRange
    name: limits
  patch: |-
    - op: replace
      path: /spec/limits/0/defaultRequest/memory
      value: 250mi