apiVersion: v1
kind: Secret
metadata:
  name: gitops-system
  namespace: gitops-system
type: Opaque
data:
  identity: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzlKVkh3ZmUwSUVxb20KMGh1WVBkTzF4MG4xNGZ2L2xHRXE1Sm51RmpHWFpKMWFkOHBWLzNqSWxrQkxKOG8zUnptdDlBUDNBR3Q5NGF6eAo3eFNHdTZrSmVwektBdGtORmx0TkdYcm9JU01kdTlLNUZncjlrRjVxZW1HSXBhL3hrVTh2MmVtT213VFZwbUxkClJLT0ZEUGs0NWhZamR4UkZ6RUc0MjZiaEJNKzh6VHFWclJNT3gxM2hQUVU5cWJ0Tlp4MEI1V1FBYStCdTJjZkoKVkIxTy9WNitWMEtOZzE5cnFZZlYrODIvU3FZQU4zYXdlZmFZUzlhVmtUSW1TZ25WZk15SHg0WE93Zm03bit4UQpkT0IyNlJBbCtkZm5LOTNkejV6d3FLZ1JSQVRFR2tXUnNua3hEODVPclp3OWtvdDc3YWJjeGZVamdyUzZEdDFHCmhGK09UamJYQWdNQkFBRUNnZ0VBQnhMbFBKeEpDQnRDbDg4Vnp4ekkxU3lOM0k5R0VHbnBOR1IyU1V3MU1KZEgKdDBGeHBNTzRMYkJJMlVhMHJscVFrcXZrbGhGQzgrTkR4NHlNZFBtQnVlUUhCeHNTS1FZa0JmOGs5SmVBcTdVQgpqWUNBaXJraWZ0THk0TnhwZHh4YkhNd0dpeG5MRlg1eWhobnlENkRMbFZBdGxjZjNUeUR6ZUVsbXRWV3J1MERWCktHTUw4Uk5taGk0NXo0Z0hrT0MxT3hMUVUzS2xMS3dGR0UxUnlXMmg4SjNNWDlrdDA4WnZ1QkdvRnZldFl1ckUKTWNnYzkzM1VMdXJwaTd1UmxxM3kxMU5VRlNtSVBGbllSeDdESmRKSld2UFlUWFdkVGl3ZXF5dkhoK21EMmN2ZwpVNmw5NmVkSURCaTgrSU8vVjE3SEJ3aXpQSzQ3ajQzV3FLbTN5cy9ld1FLQmdRRHEvaG4yLzJ3V21oT0I1SGY1CkEwa0hYV1pCaTkzYzlnOGVTMHd1ZUJKUGF6c0ZVSUUvM2JaYjNSYjZabUFJeEZiRFV6djc2RERkZXdmN2ZlbCsKRFdQdmczV1h2dHpnSmdqZ3BqSFlqSDNMcGdxMXdjVFdHdk5kYW03MVYvNkplVi8ybnZ6VkhjQ01hQnV4VVpmSwpDeDlZZkMvYW8rYjRud04wK0FqaTNXanBOd0tCZ1FET0RmOFMyeGprVGtwcU03YnJQaFBXWHROaHVSTTVIK01GCnlqdndPVU44OTluUDBJaktIeHFaNXY2QXhOV3dFNlpOazFCSXBaUGFOcm9MM3hoeHBOZWlTZmYxVW5mT2Y4Q00Kdy9PZmd4Tk4rcjQ1dUNqTjYzSWxmSkhIT2tKRXZPckNUbFFocngvWDg2WDI2Q1Qzb3UyWlNSMDYxbHJaRDA0Rgp3ckZWa29sdllRS0JnUUMrK0xvSkxSS2VXNkMyMHdGYzhQcU1iYThJWGE1MFA5T1Jmd2Z1Uzg0MWxLTm1ja0pYCnNNcmVaUktqZEVkZldKQmFORzV2RGdlSU50QUo1ZzIzVHhLRU40VjlTTE1meGtrNHFGZWg4S3Jhc1puS2xDcHYKQlgvNXp1RlZxYWxGOThteEZ3dko5bC9ndTBxbUUvVVRVVzZyN21ERmdxWFdMd1FVTHU2cHo5M09pUUtCZ0JydwpTWUMxbERPRTZNV3ByU2hrSFVQUmNlRTh5UDZXNUo5RktVRG11NlFDNHo4QURHSWdYdUh3Q1NYY2xmTkhIbDdWCis1RUQxS2lhcndnT1NxdlEyVUFtVzN4L0k1cWpxUkMrTFlPVkoxanloeHdVcjREOFh4ZjNpVGQ2cmw4K001TGoKbXF3c3NRVVNuWWdDSVpNZWdlR2daV25qekV6RWEzYmxWVG5TeHBVQkFvR0FYQVc0aXZHU0RSYzlZanBhYytscgpaRlhkRGVOaWFhYkZRUGhjSlV2QlVwWkdnNVR4bXoycXJKRzhpQVREeUUwOFZsbEg4UTgzbXJQV0VwMGNpNUNECkVZVDNMQWpSSW0xOVdteDM1aEVXWGJORThqVnRPOFVRc1l0UTJ2Q09UL2dFd21IaTZReUZlVFBQN3J2cXBXSHkKbHIvK0EyOXhzc1NoK2lLTTZjbml1MzA9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  identity.pub: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDOUpWSHdmZTBJRXFvbTBodVlQZE8xeDBuMTRmdi9sR0VxNUpudUZqR1haSjFhZDhwVi8zaklsa0JMSjhvM1J6bXQ5QVAzQUd0OTRheng3eFNHdTZrSmVwektBdGtORmx0TkdYcm9JU01kdTlLNUZncjlrRjVxZW1HSXBhL3hrVTh2MmVtT213VFZwbUxkUktPRkRQazQ1aFlqZHhSRnpFRzQyNmJoQk0rOHpUcVZyUk1PeDEzaFBRVTlxYnROWngwQjVXUUFhK0J1MmNmSlZCMU8vVjYrVjBLTmcxOXJxWWZWKzgyL1NxWUFOM2F3ZWZhWVM5YVZrVEltU2duVmZNeUh4NFhPd2ZtN24reFFkT0IyNlJBbCtkZm5LOTNkejV6d3FLZ1JSQVRFR2tXUnNua3hEODVPclp3OWtvdDc3YWJjeGZVamdyUzZEdDFHaEYrT1RqYlgK
  known_hosts: Z2l0aHViLmNvbSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFCSXdBQUFRRUFxMkE3aFJHbWRubTl0VURiTzlJRFN3Qks2VGJRYStQWFlQQ1B5NnJiVHJUdHc3UEhrY2NLcnBwMHlWaHA1SGRFSWNLcjZwTGxWREJmT0xYOVFVc3lDT1Ywd3pmaklKTmxHRVlzZGxMSml6SGhibjJtVWp2U0FIUXFaRVRZUDgxZUZ6TFFOblBIdDRFVlZVaDdWZkRFU1U4NEtlem1ENVFsV3BYTG12VTMxL3lNZitTZTh4aEhUdktTQ1pJRkltV3dvRzZtYlVvV2Y5bnpwSW9hU2pCK3dlcXFVVW1wYWFhc1hWYWw3MkorVVgyQisyUlBXM1JjVDBlT3pRZ3FsSkwzUktyVEp2ZHNqRTNKRUF2R3EzbEdIU1pYeTI4RzNza3VhMlNtVmkvdzR5Q0U2Z2JPRHFuVFdsZzcrd0M2MDR5ZEdYQThWSmlTNWFwNDNKWGlVRkZBYVE9PQo=
---
apiVersion: source.toolkit.fluxcd.io/v1alpha1
kind: GitRepository
metadata:
  name: cluster-repo
  namespace: gitops-system
spec:
  interval: 1m0s
  ref:
    branch: devel
  secretRef:
    name: gitops-system
  url: ssh://git@github.com/mberwanger/gitops-cluster1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1alpha1
kind: Kustomization
metadata:
  name: cluster1-iad-nonprod
  namespace: gitops-system
spec:
  interval: 5m
  path: ./iad/nonprod/
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-repo
