apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/calico
  - ../../../base/metrics-server
  - ../../../base/prometheus
  - ../../../base/datadog
  - ../../../base/defaults
  - ../../../base/psp
  - ../../../base/cron
